# Generated by Django 3.2.15 on 2022-09-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deepthought_title', models.TextField(max_length=200)),
                ('deepthought_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
