# Generated by Django 3.2.15 on 2022-10-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_deepthought'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepthought',
            old_name='deepthought_text',
            new_name='deepthought_description',
        ),
    ]
